name: Daily Reminder Cron

on:
  schedule:
    - cron: '37 17 * * *'  # UTC время (20:37 МСК)
  workflow_dispatch:

jobs:
  debug-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: List all available secrets
        run: |
          echo "Available secrets:"
          echo "${{ toJSON(secrets) }}" | jq -r 'keys[]'
          
          echo "Checking specific secrets:"
          echo "VERCEL_URL exists: ${{ secrets.VERCEL_URL != '' }}"
          echo "CRON_SECRET exists: ${{ secrets.CRON_SECRET != '' }}"
          
          if [ -z "${{ secrets.VERCEL_URL }}" ]; then
            echo "::error::VERCEL_URL is empty or missing"
          else
            echo "VERCEL_URL length: ${#{{ secrets.VERCEL_URL }}}"
          fi
          
          if [ -z "${{ secrets.CRON_SECRET }}" ]; then
            echo "::error::CRON_SECRET is empty or missing"
          else
            echo "CRON_SECRET length: ${#{{ secrets.CRON_SECRET }}}"
          fi
          
          # Always fail to show output
          echo "::error::This step intentionally fails to show secret diagnostics"
          exit 1

  trigger-reminder:
    needs: debug-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Trigger daily reminder
        env:
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          echo "VERCEL_URL: $VERCEL_URL"
          echo "CRON_SECRET length: ${#CRON_SECRET}"
          
          # Ваш код запроса
          curl -X POST \
            -H "Authorization: Bearer $CRON_SECRET" \
            "https://$VERCEL_URL/api/cron/daily-reminder"
