name: Daily Reminder Cron

on:
  schedule:
    - cron: '37 17 * * *'  # UTC время (20:37 МСК)
  workflow_dispatch:        # Разрешить ручной запуск

jobs:
  trigger-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger daily reminder
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
        run: |
          response_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Authorization: Bearer $CRON_SECRET" \
            "https://$VERCEL_URL/api/cron/daily-reminder")
          
          if [ "$response_code" -ne 200 ]; then
            echo "❌ Error: Received HTTP $response_code"
            exit 1
          else
            echo "✅ Success: Daily reminder triggered"
          fi
