name: Daily Reminder Cron

on:
  schedule:
    - cron: '37 17 * * *'
  workflow_dispatch:

jobs:
  trigger-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger daily reminder
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
        run: |
          # Выводим информацию для отладки (секреты не покажутся в логах)
          echo "VERCEL_URL: $VERCEL_URL"
          echo "CRON_SECRET length: ${#CRON_SECRET}"
          
          # Полный запрос с выводом ответа
          response=$(curl -i -X POST \
            -H "Authorization: Bearer $CRON_SECRET" \
            "https://$VERCEL_URL/api/cron/daily-reminder")
          
          # Выводим полный ответ для диагностики
          echo "Full response:"
          echo "$response"
          
          # Проверяем статус код
          status_code=$(echo "$response" | grep HTTP | awk '{print $2}')
          if [ "$status_code" -ne 200 ]; then
            echo "❌ Error: Received HTTP $status_code"
            exit 1
          else
            echo "✅ Success: Daily reminder triggered"
          fi
