name: Daily Reminder Cron Debug

on:
  workflow_dispatch:

jobs:
  debug-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets availability
        run: |
          echo "Diagnostic information:"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          
          # Проверка VERCEL_URL
          if [ -z "${{ secrets.VERCEL_URL }}" ]; then
            echo "::error::VERCEL_URL is MISSING"
          else
            echo "VERCEL_URL: exists (length: ${#{{ secrets.VERCEL_URL }}})"
          fi
          
          # Проверка CRON_SECRET
          if [ -z "${{ secrets.CRON_SECRET }}" ]; then
            echo "::error::CRON_SECRET is MISSING"
          else
            echo "CRON_SECRET: exists (length: ${#{{ secrets.CRON_SECRET }}})"
          fi
          
          # Всегда завершаем с ошибкой чтобы показать вывод
          echo "::error::This step intentionally fails to show diagnostic info"
          exit 1
